apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-example
spec:
  replicas: 1  # Comienza con 1 réplica para debug
  selector:
    matchLabels:
      app: devops-example
  template:
    metadata:
      labels:
        app: devops-example
    spec:
      containers:
      - name: devops-example
        image: devops-example:1.0
        imagePullPolicy: Never  # Fuerza usar imagen local
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"