name: CI/CD Pipeline with Jenkins

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t devops-example:latest .
        docker tag devops-example:latest devops-example:${{ github.sha }}
    
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
    
    - name: Push Docker image
      run: |
        docker tag devops-example:latest ${{ secrets.DOCKER_HUB_USERNAME }}/devops-example:latest
        docker tag devops-example:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/devops-example:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/devops-example:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/devops-example:${{ github.sha }}
    
    - name: Trigger Jenkins Deployment
      uses: fjogeleit/http-request-action@v1
      with:
        url: '${{ secrets.JENKINS_URL }}/generic-webhook-trigger/invoke?token=${{ secrets.JENKINS_TOKEN }}'
        method: 'POST'
        data: '{"image_name":"${{ secrets.DOCKER_HUB_USERNAME }}/devops-example","image_tag":"${{ github.sha }}","commit_sha":"${{ github.sha }}"}'
        customHeaders: '{"Content-Type":"application/json","Authorization":"Bearer ${{ secrets.JENKINS_TOKEN }}"}'